In [56]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
import numpy as np

In [57]:
reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']

In [58]:
sentiments = np.array([1,0,1,1,0,1,0,0,0,1])

## Let's do one hot encoding 

In [59]:
one_hot("needs improvement",20)

[4, 7]

In [60]:
size = 50
encoded_rev = [one_hot(d,size) for d in reviews]
print(encoded_rev)

[[1, 7], [44, 13], [49, 29], [15, 8, 15], [1, 40, 20], [26, 7], [40, 40, 2], [18, 6], [18, 22], [34, 12]]


In [61]:
max_len = 4
padded_rev = pad_sequences(encoded_rev, maxlen = max_len, padding='post')
print(padded_rev)

[[ 1  7  0  0]
 [44 13  0  0]
 [49 29  0  0]
 [15  8 15  0]
 [ 1 40 20  0]
 [26  7  0  0]
 [40 40  2  0]
 [18  6  0  0]
 [18 22  0  0]
 [34 12  0  0]]


In [62]:
embedd_d_vec = 5
model = Sequential()
model.add(Embedding(size,embedd_d_vec,input_length=max_len, name = 'embedding'))
model.add(Flatten())
model.add(Dense(1,activation= 'sigmoid'))

In [63]:
X = padded_reviews
y = sentiments

In [64]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
print(model.summary())

Model: "sequential_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 4, 5)              250       
                                                                 
 flatten_5 (Flatten)         (None, 20)                0         
                                                                 
 dense_5 (Dense)             (None, 1)                 21        
                                                                 
Total params: 271
Trainable params: 271
Non-trainable params: 0
_________________________________________________________________
None


In [65]:
model.fit(X,y,epochs = 5)

Epoch 1/5
1/1 [==============================] - 0s 367ms/step - loss: 0.6975 - accuracy: 0.4000
Epoch 2/5
1/1 [==============================] - 0s 11ms/step - loss: 0.6962 - accuracy: 0.4000
Epoch 3/5
1/1 [==============================] - 0s 4ms/step - loss: 0.6950 - accuracy: 0.5000
Epoch 4/5
1/1 [==============================] - 0s 3ms/step - loss: 0.6937 - accuracy: 0.6000
Epoch 5/5
1/1 [==============================] - 0s 4ms/step - loss: 0.6925 - accuracy: 0.6000


In [66]:
# evaluate the model
loss, accuracy = model.evaluate(X, y)
accuracy

1/1 [==============================] - 0s 82ms/step - loss: 0.6912 - accuracy: 0.6000


0.6000000238418579

In [67]:
weights = model.get_layer('embedding').get_weights()[0]
len(weights)

50

In [68]:
weights[13]


array([ 0.0083785 , -0.01360647,  0.00419767,  0.03186557,  0.0299108 ],
      dtype=float32)

In [70]:
weights[1]


array([ 0.04981953, -0.03774847, -0.033667  , -0.00919856,  0.02253211],
      dtype=float32)